In [34]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor
)
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error
from sklearn.decomposition import PCA

from xgboost import XGBRegressor

In [35]:
df = pd.read_csv(r'C:\Users\ACER\Desktop\Projects\Machine Learning Based Real Estate System\Dataset\Cleaned_Properties_V5_Post_Feature_Selection_V2.csv')

In [36]:
df.head()

  property_type      sector  ...  luxury_category  floor_category
0          flat   sector 36  ...              Low       Low Floor
1          flat   sector 89  ...              Low       Mid Floor
2          flat  sohna road  ...              Low      High Floor
3          flat   sector 92  ...             High       Mid Floor
4          flat  sector 102  ...             High       Mid Floor

[5 rows x 13 columns]

In [37]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [38]:
# 0 - unfurnished
# 1 - semifurnished
# 2 - furnished

df['furnishing_type'] = df['furnishing_type'].replace({
    0.0: 'unfurnished',
    1.0: 'semifurnished',
    2.0: 'furnished'
})

In [39]:
df.head()

  property_type      sector  ...  luxury_category  floor_category
0          flat   sector 36  ...              Low       Low Floor
1          flat   sector 89  ...              Low       Mid Floor
2          flat  sohna road  ...              Low      High Floor
3          flat   sector 92  ...             High       Mid Floor
4          flat  sector 102  ...             High       Mid Floor

[5 rows x 13 columns]

#### Train Test Split

In [40]:
X = df.drop(columns=['price'])
y = df['price']

In [41]:
# Applying the Log1p Transformation to the Target variable
y_transformed = np.log1p(y)

### Ordinal Encoding

In [42]:
columns_to_encode = ['property_type', 'sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

In [43]:
# Creating a Column Transformer for PreProcessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode)
    ],
    remainder='passthrough'
)

In [44]:
# Creating a Pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [45]:
# K-Fold Cross Validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [46]:
scores.mean(), scores.std()

(np.float64(0.7363096633436828), np.float64(0.03238005754429936))

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size=0.2, random_state=42)

In [48]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [49]:
y_pred = pipeline.predict(X_test)

In [50]:
y_pred = np.expm1(y_pred)

In [51]:
mean_absolute_error(np.expm1(y_test), y_pred)

0.9463822160089356

In [52]:
def scorer(model_name, model):
    
    output = []
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-Fold Cross validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size=0.2, random_state=42)
    
    pipeline.fit(X_train, y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test), y_pred))
    
    return output

In [53]:
model_dict = {
    'Linear Regression':LinearRegression(),
    'Support Vector Regressors': SVR(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'Decision Tree': DecisionTreeRegressor(),
    'Random Forest': RandomForestRegressor(),
    'Extra Trees': ExtraTreesRegressor(),
    'Gradient Boosting': GradientBoostingRegressor(),
    'AdaBoost': AdaBoostRegressor(),
    'MLP': MLPRegressor(),
    'XGBoost': XGBRegressor(),
}

In [54]:
model_output = []
for model_name, model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [55]:
model_df = pd.DataFrame(model_output, columns=['name', 'r2', 'mae'])

In [56]:
model_df.sort_values(['mae'])

                         name        r2       mae
10                    XGBoost  0.889488  0.504048
5               Random Forest  0.881077  0.532642
6                 Extra Trees  0.867589  0.549143
7           Gradient Boosting  0.872624  0.576690
9                         MLP  0.814078  0.702691
4               Decision Tree  0.776276  0.730651
1   Support Vector Regressors  0.764201  0.847264
8                    AdaBoost  0.753216  0.857732
2                       Ridge  0.736313  0.946339
0           Linear Regression  0.736310  0.946382
3                       Lasso  0.059434  1.528906

### OneHotEncoding